// frontend/features/editor/extensions/video/extension.tsx
import { type Attribute, Node } from '@tiptap/core'
// ...
import { NodeViewWrapper, SolidNodeViewRenderer } from '~/libs/solid-tiptap-renderer'
// ...
import { insertNodeAtCurrentPosition, useNodeState } from '../../utils'
import { Video, type VideoAttribute } from '../files'

declare module '@tiptap/core' {
  interface Commands<ReturnType> {
    video: {
      insertVideo$: () => ReturnType
    }
  }
}

export const VideoNode = Node.create({
  name: 'video',
  group: 'inline',
  inline: true,
  selectable: false,
  atom: true,
  addAttributes(): Record<keyof VideoAttribute, Attribute> {
    return {
      name: {
        default: null,
      }
    }
  },
  addCommands() {
    return {
      insertVideo$: () => ({ tr }) => {
        return insertNodeAtCurrentPosition<VideoAttribute>(this, tr, { name: '' })
      },
    }
  },
  addNodeView: () => SolidNodeViewRenderer(() => {
    const { data$ } = useNodeState<VideoAttribute>()

    return (
      <NodeViewWrapper>
        <Video src$={data$().name} />
      </NodeViewWrapper>
    )
  }),
})

// frontend/features/editor/extensions/table/extension.tsx
import { lazy } from 'solid-js'
import { type Attribute, Node } from '@tiptap/core'
// ...
import { SolidNodeViewRenderer } from '~/libs/solid-tiptap-renderer'
import { makeId } from '~/utils'
// ...
import { insertNodeAtCurrentPosition } from '../../utils'
import type { TableAttribute } from './provider'

declare module '@tiptap/core' {
  interface Commands<ReturnType> {
    table: {
      insertTable$: () => ReturnType
    }
  }
}

const TableNodeView = lazy(() => import("./node"))

export const TableExtension = Node.create({
  name: 'table',
  group: 'block',
  inline: false,
  selectable: false,
  atom: true,
  addAttributes(): Record<keyof TableAttribute, Attribute> {
    return {
      id: {
        default: ''
      },
    }
  },
  addCommands() {
    return {
      insertTable$: () => ({ tr }) => {
        return insertNodeAtCurrentPosition<TableAttribute>(this, tr, { 
          id: '',
        })
      },
    }
  },
  addNodeView: () => SolidNodeViewRenderer(TableNodeView),
})
